name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  windows-x64:
    runs-on: windows-2022
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-x64

      - name: Build
        run: cmake --build --preset windows-x64

      - name: Test
        run: ctest --preset windows-x64

      - name: Package
        run: cmake --build build/windows-x64 --config Release --target PACKAGE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/windows-x64/SimpleFiler-*-windows-x64.zip
